import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import NavBar from '@/components/NavBar/NavBar'
import Hero from '@/components/Hero/Hero'
import Cryptos from '@/components/Cryptos/Cryptos'
import Assets from '@/components/XMAssets/Assets'
import Register from '@/components/Register/Register'
import EventGallery from '@/components/Gallery/Gallery'
import Values from '@/components/XMValues/Values'
import Footer from '@/components/Footer/Footer'


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <NavBar/>
      <main className={styles.main}>
        <div className={styles.tintHeader}></div>
        <Hero/>
        <Cryptos/>
        <Assets/>
        <Register/>
        <EventGallery/>
        <Values/>
        <Footer/>
      </main>
    </>
  )
}
